from app.Dash_Logistica.kpis_luiz.main import kpi_entregues_no_prazo,kpi_pedidos_ja_atrasados,kpi_time_logistica,kpi_time_transporte,kpi_pedido_perfeito,kpi_dock_stock_time,kpi_acuracidade_do_sistema

print(kpi_acuracidade_do_sistema)